"""empty message

Revision ID: 9749ee10cc12
Revises: eb0b8ef941bc
Create Date: 2023-02-10 11:30:04.341159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9749ee10cc12'
down_revision = 'eb0b8ef941bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=True))
        batch_op.drop_column('looking_for_talent')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=True))
        batch_op.drop_column('looking_for_talent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_talent')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
